/** @jsxImportSource @emotion/react */

import Head from 'next/head'

export default function Home() {
  const mainStyle = {
    width: "100%",
    display: "flex",
    flexDirection: "column" as const,
    justifyContent: "center" as const,
    alignItems: "center",
    minHeight: "100vh"
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main css={mainStyle}>
        <h1>Bundle Next.js</h1>
        <p>With Emotion, Styled Component and css Prop</p>
      </main>
    </>
  )
}
